### ISSUE TITLE
Console Spammer Issue

### ISSUE THREAD

**Issue by Fanyhsiao** [gykkuo/MIUI_NoGuard#1]
I cloned this repositorie and test on my phone mobile.It runs well but a issue that trouble me a lot.I used another module that need print some useful debug information but this module will make my console be in spammed.Can you help me or fix it?
![Uploading -7bbd796545cf9f9.jpg…]()

**Comment by ImFl0wow** [comment]
![Screenshot_2023-08-14-23-01-31-599_com microsoft emmx](https://github.com/gykkuo/MIUI_NoGuard/assets/61338229/1142dbcc-39f0-4cf0-8305-47c8b1668fb6)

**Comment by Fanyhsiao** [comment]
![-7bbd796545cf9f9](https://github.com/gykkuo/MIUI_NoGuard/assets/61338229/73c2d2c2-c197-40fb-828a-3e5d2c4c7fd8)

**Comment by gykkuo** [comment]
> ![-7bbd796545cf9f9](https://github.com/gykkuo/MIUI_NoGuard/assets/61338229/73c2d2c2-c197-40fb-828a-3e5d2c4c7fd8)
> 

I see.It will be fixed in next version.
