### ISSUE TITLE
向kuo大你反馈下此存储库Release中1.0.2版安装包上传错误问题

### ISSUE THREAD

**Issue by P3R5T7U9** [gykkuo/MIUI_NoGuard#2]
今天才在某安了解到这个xp模块，也正是我近期在找可防止MIUI14自动上传用户已安装应用列表此需求的实现模块，先感谢kuo大开发此模块👍

不过无论我在Github上Lsp模块仓库中这个模块的存储库中的Release部分，还是在此存储库中Release部分，发现1.0.2版的安装包下载到本地，用MT管理器查看安装包信息，显示其是1.0.1版的安装包。。。

感觉kuo大当初在上传1.0.2版安装包是不是误将1.0.1版安装包上传？？为避免kuo大不信我所反馈的问题，已将问题情况录制成动图，上传到图床上(由于动图比较大，我以md语法粘贴图床链接到issue里，一直加载不出来动图)，只好贴上该动图在图床上地址，麻烦kuo大点击图床外链跳转查看了，图床外链如下：
https://ibb.co/K0Q6frp

麻烦kuo大回复并重传此模块的1.0.2版安装包惹😖

**Comment by gykkuo** [comment]
1.0.2没有修改apk版本号，但release的版本号是1.0.2。
感谢指出问题，往后不会再出现此类问题。

**Comment by gykkuo** [comment]
您可以看下lsposed里面的日志，有没有原1.0.1的日志输出问题。没有即使用的是1.0.2。

**Comment by P3R5T7U9** [comment]
> 您可以看下lsposed里面的日志，有没有原1.0.1的日志输出问题。没有即使用的是1.0.2。

才看到kuo大你在早上的回复，一开始没明白1.0.1版的日志输出问题是指什么，随后到release中1.0.2版更新说明指路的 #1 翻阅这条issue反馈内容，才明白是指1.0.1版会在lsposed的日志中无限刷屏问题，立马打开lsposed的日志界面看了下，kuo大你开发的“MIUI_NoGuard”日志雀食只输出到成功拦截就停止了，按kuo大你回复中提到1.0.2版的日志特征，我使用的应该就是1.0.2版的包
(小声：虽说这一版的apk版本号仍旧为1.0.1版😖)

**Comment by gykkuo** [comment]
我会注意，不会再出现这样的问题了。
（小声：某安的哪个帖子有上传我的模块，我想看看）

**Comment by P3R5T7U9** [comment]
> 我会注意，不会再出现这样的问题了。 （小声：某安的哪个帖子有上传我的模块，我想看看）

抱歉我又回复迟了，我这边才注意到kuo大你在中午发的回复(github的提醒邮件)

我最初发的反馈内容中所提到“在某安了解到这个模块”，不是指我当初在某安看到一酷友专门发帖分享及介绍此模块，而是我前段时间在某安的“Xposed模块”这个话题区，翻看一些酷友对几个模块的问题讨论帖时，偶然看到一酷友在某个帖子(具体哪个帖子，我刚回到某安翻找了半个多小时，还是没找到，当时忘了收藏，也没想到之后开这条issue反馈问题时，kuo大你想看我提到的了解来源😖)评论区发了张他自己手机在lsp管理器中已安装的xp模块列表截图，看到他装了kuo大你开发的这个模块；

由于之前从未了解过这个模块，再加上我个人有极强的溯源意识，当时猜测这个模块的原发布地址就在github的lsp官方创建的xp模块仓库里，随后立马打开github，奔xp模块仓库而来，从上往下翻模块没过几个，果不其然翻到这个模块，也怪我当初发这条issue时没写清楚，导致kuo大你理解歧义了

**Comment by P3R5T7U9** [comment]
> 我会注意，不会再出现这样的问题了。 （小声：某安的哪个帖子有上传我的模块，我想看看）

另外，歪个楼，之前也一直在找“ZygiskOnKernelSU”这个面具模块，刚“手贱”点进kuo大你的github 个人主页，发现kuo大你这段时间fork过“ZygiskOnKernelSU”仓库，而且在官方源码基础上进一步优化，瞬间大喜过望，但高兴没几秒，又发现kuo大你fork并优化的“ZygiskOnKernelSU”在Release 或 Action中上传成品模块。。。

随后又看到该仓库文件夹有个名为“module”文件夹，点进去后一看是面具模块的各组成子文件，如果我要刷kuo大你优化过的“ZygiskOnKernelSU”模块，猜测先以.zip形式下载kuo大你fork的“ZygiskOnKernelSU”这个仓库所有文件，然后解包，将“module”这个文件夹单独移到它处，再将这个文件夹添加后缀为.zip，再刷入到Magisk，不知这样操作可成功刷入kuo大你优化的“ZygiskOnKernelSU”模块么？？
(小声：还是麻烦kuo大有时间将个人优化的“ZygiskOnKernelSU”制作为成品传到Release 或 Action中😖)

**Comment by gykkuo** [comment]
> > 我会注意，不会再出现这样的问题了。 （小声：某安的哪个帖子有上传我的模块，我想看看）
> 
> 另外，歪个楼，之前也一直在找“ZygiskOnKernelSU”这个面具模块，刚“手贱”点进kuo大你的github 个人主页，发现kuo大你这段时间fork过“ZygiskOnKernelSU”仓库，而且在官方源码基础上进一步优化，瞬间大喜过望，但高兴没几秒，又发现kuo大你fork并优化的“ZygiskOnKernelSU”在Release 或 Action中上传成品模块。。。
> 
> 随后又看到该仓库文件夹有个名为“module”文件夹，点进去后一看是面具模块的各组成子文件，如果我要刷kuo大你优化过的“ZygiskOnKernelSU”模块，猜测先以.zip形式下载kuo大你fork的“ZygiskOnKernelSU”这个仓库所有文件，然后解包，将“module”这个文件夹单独移到它处，再将这个文件夹添加后缀为.zip，再刷入到Magisk，不知这样操作可成功刷入kuo大你优化的“ZygiskOnKernelSU”模块么？？
> 「小声：还是麻烦kuo大有时间将个人优化的“ZygiskOnKernelSU”制作为成品传到Release 或 Actions(估计需要kuo大再向ci.yaml文件中添加自动编译模块并上传到action的代码)」

我没有优化ZygiskOnKernelSU，只是fork了而已。其实我也只是入门的开发者。

**Comment by gykkuo** [comment]
有问题的话，还请多发issue。

**Comment by P3R5T7U9** [comment]
> 有问题的话，还请多发issue。

今早比较忙，又是刚才看到github推送kuo大你在凌晨的回复提醒邮件。

主要kuo大你在fork的“ZygiskOnKernelSU”仓库设置中没开启Issue板块，所以昨天只好在“MIUI_NoGuard”这个仓库的Issue板块下歪楼提问了。

**Comment by P3R5T7U9** [comment]
> 我没有优化ZygiskOnKernelSU，只是fork了而已。其实我也只是入门的开发者。

但我昨天在翻阅kuo大你fork的“ZygiskOnKernelSU”此仓库的历史commit时，看kuo大你在官方源码基础上还提交了6个commit，如下截图所圈部分：
![](https://i.ibb.co/Q8vR0sm/IMG-20230829-110440.jpg)

(小声：而且fork仓库中也显示“This branch is 6 commits ahead of Dr-TSNG:master”，我也是看到这条被误导以为kuo大你对“ZygiskOnKernelSU”进一步优化)

还有我昨天对kuo大你所fork的“ZygiskOnKernelSU”仓库无成品模块，制作成品模块步骤是否正确的小提问也写在这条comment的第二段，如下截图所圈部分：
![](https://i.ibb.co/nb1tTCh/IMG-20230829-111639.jpg)

貌似kuo大没看到我，只回复我在这条comment中第一段内容，再求kuo大对我昨天发的这条comment中第二段内容回复下呗

**Comment by gykkuo** [comment]
> > 我没有优化ZygiskOnKernelSU，只是fork了而已。其实我也只是入门的开发者。
> 
> 但我昨天在翻阅kuo大你fork的“ZygiskOnKernelSU”此仓库的历史commit时，看kuo大你在官方源码基础上还提交了6个commit，如下截图所圈部分：
> ![](https://i.ibb.co/Q8vR0sm/IMG-20230829-110440.jpg)
> 
> (小声：而且fork仓库中也显示“This branch is 6 commits ahead of Dr-TSNG:master”，我也是看到这条被误导以为这6个commit是kuo大你对“ZygiskOnKernelSU”这个模块再进一步优化)
> 
> 还有我昨天对kuo大你所fork的“ZygiskOnKernelSU”仓库无成品模块，制作成品模块步骤是否正确的小提问也写在这条comment的第二段，如下截图所圈部分：
> ![](https://i.ibb.co/nb1tTCh/IMG-20230829-111639.jpg)
> 
> 貌似kuo大没看到我，只回复我在这条comment中第一段内容，再求kuo大对我昨天发的这条comment中第二段内容回复下呗

应该不行，有些东西没编译。我也不确定，只是fork了。
